server:
  port: 8080
  host: localhost
  
database:
  type: postgres
  connection: "host=localhost user=postgres password=postgres dbname=mediaCircle port=5432 sslmode=disable TimeZone=UTC"
  
logging:
  level: debug
  format: text